In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("../data/raw/Online Retail.csv")

In [3]:
data.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 8.26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 8.26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 8.26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 8.26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 8.26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,01-12-2010 8.26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,01-12-2010 8.26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,01-12-2010 8.28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,01-12-2010 8.28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,01-12-2010 8.34,1.69,13047.0,United Kingdom

In [4]:
data.shape

(541909, 8)

In [5]:
data.info()
# In Customer Id there are 135080 null values 
# In Description there are 1454 null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [6]:
data.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [7]:
# There must be some outliers as max quantities are 80995 and minimum is -80995 
# similarly in unit price , minimum is -11062 also max is 38970

In [8]:
data.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900,4070,4223,NaN,23260,NaN,NaN,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,31-10-2011 14.41,NaN,NaN,United Kingdom
freq,1114,2313,2369,NaN,1114,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,NaN,4.611114,15287.690570,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN
min,NaN,NaN,NaN,-80995.000000,NaN,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,NaN,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,NaN,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,NaN,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,NaN,38970.000000,18287.000000,NaN

In [9]:
data["CustomerID"].nunique()
# There are only 4372 Customers

4372

In [10]:
data["InvoiceNo"].nunique()
# means every cumtomer averagly buy for 5 times

25900

In [13]:
# How much customer purchase??
df = data.groupby("CustomerID")["InvoiceNo"].value_counts().reset_index()
round(df.groupby("CustomerID")["count"].mean(),2)
# plt.tight_layout()

CustomerID
12346.0     1.00
12347.0    26.00
12348.0     7.75
12349.0    73.00
12350.0    17.00
           ...
18280.0    10.00
18281.0     7.00
18282.0     4.33
18283.0    47.25
18287.0    23.33
Name: count, Length: 4372, dtype: float64

In [14]:
data.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [22]:
# Checked duplicated rows 
data[data.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,01-12-2010 11.45,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,01-12-2010 11.45,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,01-12-2010 11.45,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,01-12-2010 11.45,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,01-12-2010 11.49,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,09-12-2011 11.34,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,09-12-2011 11.34,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,09-12-2011 11.34,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,09-12-2011 11.34,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,09-12-2011 11.34,2.08,14446.0,United Kingdom

In [29]:
Total_Quantity_bought_by_customer = data.groupby("CustomerID")["Quantity"].sum().reset_index()

In [30]:
# How much quantity bought by customer
Total_Quantity_bought_by_customer

      CustomerID  Quantity
0        12346.0         0
1        12347.0      2458
2        12348.0      2341
3        12349.0       631
4        12350.0       197
...          ...       ...
4367     18280.0        45
4368     18281.0        54
4369     18282.0        98
4370     18283.0      1397
4371     18287.0      1586

[4372 rows x 2 columns]

In [32]:
Total_Quantity_bought_by_customer = data.groupby("CustomerID").agg({
    "Quantity":"sum",
    "UnitPrice":"sum"
})

In [33]:
Total_Quantity_bought_by_customer

            Quantity  UnitPrice
CustomerID
12346.0            0       2.08
12347.0         2458     481.21
12348.0         2341     178.71
12349.0          631     605.10
12350.0          197      65.30
...              ...        ...
18280.0           45      47.65
18281.0           54      39.36
18282.0           98      62.68
18283.0         1397    1220.93
18287.0         1586     104.55

[4372 rows x 2 columns]

In [35]:
data[data["CustomerID"]==12346]
# Here Quantity of 12346 CustomerID are +74215 , -74215

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,18-01-2011 10.01,1.04,12346.0,United Kingdom
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,18-01-2011 10.17,1.04,12346.0,United Kingdom

In [36]:
data[data["UnitPrice"]==1.04]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,18-01-2011 10.01,1.04,12346.0,United Kingdom
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,18-01-2011 10.17,1.04,12346.0,United Kingdom
148290,549222,23076,ICE CREAM SUNDAE LIP GLOSS,240,07-04-2011 10.43,1.04,12347.0,Iceland
170413,551292,23078,ICE CREAM PEN LIP GLOSS,96,27-04-2011 14.27,1.04,14298.0,United Kingdom
170414,551292,23077,DOUGHNUT LIP GLOSS,60,27-04-2011 14.27,1.04,14298.0,United Kingdom
...,...,...,...,...,...,...,...,...
534311,C581145,23250,VINTAGE RED TRIM ENAMEL BOWL,-38,07-12-2011 13.48,1.04,17490.0,United Kingdom
534934,581175,23483,HANGING BUTTERFLY T-LIGHT HOLDER,72,07-12-2011 15.16,1.04,14646.0,Netherlands
540301,581476,23166,MEDIUM CERAMIC TOP STORAGE JAR,48,09-12-2011 8.48,1.04,12433.0,Norway
540418,581482,23251,VINTAGE RED ENAMEL TRIM MUG,96,09-12-2011 9.08,1.04,17490.0,United Kingdom
541745,581571,23168,CLASSIC CAFE SUGAR DISPENSER,36,09-12-2011 12.00,1.04,15311.0,United Kingdom

In [37]:
# Unique Values
data["Description"].nunique()

4223

In [38]:
data["StockCode"].nunique()

4070

In [39]:
data["Country"].nunique()

38

In [40]:
data["InvoiceNo"].nunique()

25900

In [50]:
(data["Quantity"]<0).sum()
# There are 10000 CustomerID has negative quantities

np.int64(10624)

In [51]:
(data["Quantity"]>0).sum()

np.int64(531285)

In [52]:
(data["UnitPrice"]<=0).sum()
# there are 2517 negative values

np.int64(2517)

In [53]:
(data["InvoiceNo"].str.startswith("C")).sum()
# There are 9288 cancelled transactions

np.int64(9288)

In [55]:
# there are 4372 customers 
# there are 135080 missing customerId  
# there are 9288 cancellations 
# there are 10000 negative Quantities
# there are 25900 unique invoices 
# there are 38 countries